version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL: '172.19.0.1'
      AUTH_PORT: '4000'
      AUTH_USERS_ENTRY: 'sa-auth-ms/resources/users'
      #NOTIFICATION_URL: '172.27.0.3'
      NOTIFICATION_PORT: '4001'
      NOTIFICATION_ENTRY: 'notifications'
      #USERS_URL: '172.25.0.3'
      USERS_PORT: '4002'
      USERS_ENTRY: 'users'
      STATES_URL: '172.19.0.3'
      STATES_PORT: '8000'
      STATES_ENTRY: 'api/States'
    ports:
      - '5000:5000'
