version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL: '172.17.0.1'
      AUTH_PORT: '4000'
      AUTH_USERS_ENTRY: 'sa-auth-ms/resources/users'
      NOTIFICATION_PORT: '4001'
      NOTIFICATION_ENTRY: 'notifications'
      USERS_PORT: '4002'
      USERS_ENTRY: 'users'
      STATES_PORT: '8000'
      STATES_ENTRY: 'api/States'
      MULTIMEDIA_PORT: '8081'
      MULTIMEDIA_ENTRY: '/entries'
    ports:
      - '5000:5000'
